codecov:
  token: c65c7228-e192-4e4f-b179-ab8ce4f72f78
coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "test/"  # only include coverage in "tests/" folder
      app:  # declare a new status context "app"
        paths: "!test/"  # remove all files in "tests/"